# Generated by EventFlow CI on Mon Apr 21 03:15:20 UTC 2025.
# DO NOT EDIT.

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /App

ENV PATH="${PATH}:/root/.dotnet/tools"

# Download archive
ADD https://github.com/EvntFlow/EventFlow_CI/releases/latest/download/eventflow.tar.gz eventflow.tar.gz
RUN tar -xzf eventflow.tar.gz && rm -f eventflow.tar.gz

# Load development secrets & copy for publish
RUN --mount=type=secret,id=appsettings_Secrets_json,dst=/etc/secrets/appsettings.Secrets.json     cp /etc/secrets/appsettings.Secrets.json .

# Synchronize database state
RUN ./DbUpdate

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /App
COPY --from=build-env /App .
ENTRYPOINT ["dotnet", "EventFlow.dll"]


